In [1]:
# import numpy as np
# import subprocess
# from datetime import datetime, timedelta
# import multiprocessing as mp
# import sys, time
# from countdown import countdown
# import av
# import glob
# import serial
# from tqdm import tqdm
# import numpy as np
# import matplotlib.pyplot as plt
# import os, time, serial, glob, struct

In [14]:
from multicamera_acquisition.interfaces.arduino import (
    packIntAsLong,
    wait_for_serial_confirmation,
)
import numpy as np

from multicamera_acquisition.interfaces import get_camera
from multicamera_acquisition.video_io import write_frame
from multicamera_acquisition.paths import ensure_dir
from multicamera_acquisition.acquisition import acquire_video

from pypylon import pylon

In [2]:
def packIntAsLong(value):
    """Packs a python 4 byte integer to an arduino long"""
    return struct.pack('i', value)

    
def get_timing_params(duration, framerate, exposure_time, buffer=50):
    
    inv_framerate = int(1e6/framerate)
    num_cycles = int(duration * framerate / 2)
    
    params = (
        num_cycles,
        exposure_time,
        inv_framerate,
    )
    
    return params
    


In [3]:
%load_ext autoreload
%autoreload 2



## Set up the camera

In [53]:
# cam = get_camera(brand='pylon', exposure_time=1000, readout_mode='Normal')


recording_duration_s = 10*60
# recording_duration_s = 6
save_location = '/home/dattalab4/Desktop/23_1_24_basler_6cam/JP_testing/trigger_test/20230313_trigger_test/'

camera_list = [
    {'name': 'side4',  'serial': 24535665, 'brand':'basler', 'gain': 0, 'exposure_time':1100, 'gpu':0, "display":False, 'roi':(0,192,1280,832)},
    {'name': 'side1',  'serial': 24548223, 'brand':'basler', 'gain': 0, 'exposure_time':1100, 'gpu':1, "display":False, 'roi':(0,192,1280,832)},
    {'name': 'bottom', 'serial': 24562650, 'brand':'basler', 'gain': 0, 'exposure_time':1000, 'gpu':1, "display":False},
    {'name': 'top',    'serial': 24562653, 'brand':'basler', 'gain': 0, 'exposure_time':1100, 'gpu':1, "display":False},
#     {'name': 'side3',  'serial': 24562655, 'brand':'basler', 'gain': 0, 'exposure_time':1100, 'gpu':1, "display":False, 'roi':(0,192,1280,832)}
]

In [54]:
acquire_video(
    save_location,
    camera_list,
    azure_framerate = 30,  # azure's frame rate in this case.
    basler_framerate=120,
    recording_duration_s = recording_duration_s,
    serial_timeout_duration_s=0.1,
    overwrite=False,
    append_datetime=True,
    verbose=True
)

Confirmation recieved: Start



recording progress (s):   0%|                           | 0/600 [00:00<?, ?it/s]

Num cycles:18000
320,8195,16528,24861,
1895,9770,18103,26436,



recording progress (s):  32%|█████▍           | 194/600 [03:14<06:47,  1.00s/it]


recording progress (s):  65%|██████████▉      | 388/600 [06:29<03:32,  1.00s/it]


recording progress (s):  97%|████████████████▍| 582/600 [09:43<00:18,  1.00s/it]


recording progress (s): 100%|████████████████▉| 597/600 [09:58<00:03,  1.00s/it]

Finished
End Acquisition


File does not exist
Frames (side4): None
Frames (side1): 71996
Frames (bottom): 71996
Frames (top): 71996


PosixPath('/home/dattalab4/Desktop/23_1_24_basler_6cam/JP_testing/trigger_test/20230313_trigger_test/23-03-13-14-37-11-026545')

In [37]:
np.arange(10)*1575

array([    0,  1575,  3150,  4725,  6300,  7875,  9450, 11025, 12600,
       14175])

In [23]:
import numpy as np
np.diff(np.array([370,8245,16528,24861, 33333+370]))

array([7875, 8283, 8333, 8842])

In [25]:
np.diff(np.array([3520,11395,19678,28011, 33333+3520]))

array([7875, 8283, 8333, 8842])